# --- Site basics
title: FIREandLife
url: https://livefireandlife.com
baseurl: ""                # at domain root
permalink: /:categories/:title/
markdown: kramdown

# --- Tell Jekyll where your site actually lives
source: src                # look inside /src for pages
layouts_dir: _layouts      # /src/_layouts
includes_dir: _includes    # /src/_includes

# --- Plugins (all supported on GitHub Pages/Netlify)
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# --- What NOT to process
exclude:
  - node_modules
  - dist
  - .eleventy.js
  - package.json
  - package-lock.json
  - netlify.toml
  - Gemfile
  - Gemfile.lock