title: FIREandLife
url: https://livefireandlife.com
baseurl: ""                # domain root
permalink: /:categories/:title/
markdown: kramdown

# Jekyll paths
source: src                # <— content lives here
destination: _site

# Optional: if you later move assets under src/assets, they'll be copied automatically
# defaults:
#   - scope: { path: "" }
#     values: { layout: default }

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Keep the build clean
exclude:
  - node_modules
  - dist
  - .eleventy.js
  - package.json
  - package-lock.json
  - netlify/functions
